package com.magiconcall.domain.incident;

public enum IncidentEventType {
    CREATED,
    STATUS_CHANGED,
    HYPOTHESIS_ADDED,
    EVIDENCE_ADDED,
    ACTION_TAKEN,
    NOTE_ADDED,
    ALERT_CORRELATED,
    TOOL_EXECUTED,
    TRIAGE_COMPLETED,
    GRAPH_NODE_ADDED,
    GRAPH_SEEDED,
    ACTION_PROPOSED,
    ACTION_APPROVED,
    ACTION_REJECTED,
    ACTION_EXECUTED,
    ACTION_FAILED
}
